version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: ["./wait-for-it.sh", "db:3306", "--", "java", "-jar", "app.jar"]

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: medic
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
